
title: Shanmukha Karthik
url: 'https://github.com/shanmukhakarthik'
baseurl: '/portfolio' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Shanmukha Karthik
tagline: Aspiring Data scientist
pic: Camera360_2015_4_3_104926.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: shanmukhakarthik@hotmail.com
phone: +91-9177079923
linkedin: shanmukha-karthik-a91b9b33
github: shanmukhakarthik





# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
